### ISSUE TITLE
The docs doesn't specify which values are required

### ISSUE THREAD

**Issue by dexax** [khashashin/django-appwrite#7]
So I have been checking the code of this plugin.
And it looks like the `PROJECT_API_KEY` is not  begin used at all.  
So you could just provide empty string and it will be still running.

So maybe it's worth to mention in the docs that this particular setting is there only for future
usecases like the groups/memberships check for permission or something?.

**Comment by khashashin** [comment]
Thank you for bringing this to my attention, @dexax! You are correct that providing an empty string for `PROJECT_API_KEY` doesn’t raise an immediate error. However, this key is crucial for fetching user account information, as outlined in the [configuration guide](https://github.com/khashashin/django-appwrite#configuration). Without a valid `PROJECT_API_KEY`, any attempts to retrieve user information will result in errors.

I appreciate your suggestion and will consider clarifying this in the documentation. Highlighting the importance of `PROJECT_API_KEY` and its role in user information retrieval can indeed help future users avoid potential issues. If you have any further questions or suggestions, please feel free to share them!

**Comment by dexax** [comment]
I have just check it against Appwrite 1.4.3
with SDK in version 2.0.2
In scenario described below you can see, you don't need `PROJECT_API_KEY` to retrieve information about JWT owner:


```
from appwrite import client
from appwrite.services import accounts
client =client.Client()
client.set_endpoint("http://localhost:80/v1")
client.set_project("<YOUR_PROJECT_ID>")
client.set_jwt("<YOUR_JWT>")
account_service = accounts.Account(client)
account_service.get()
// gets JWT owner information
```

**Comment by khashashin** [comment]
Thank you for your diligence in verifying this, @dexax! You're indeed correct, and I appreciate your effort in testing this out. The `PROJECT_API_KEY` is not required for retrieving JWT owner information, but it becomes essential when accessing the users API of Appwrite as per the [official documentation](https://appwrite.io/docs/references/1.4.x/server-python/users#get).

Your insight is valuable, and it has led me to reevaluate the necessity of `PROJECT_API_KEY` for the current functionality of the `django-appwrite` package. Considering your findings, it seems that this key might not be needed. As a result, I am planning to remove it in upcoming releases to streamline the configuration process and avoid any unnecessary complexities.

If you have any more observations or suggestions, please don’t hesitate to share them!

**Comment by khashashin** [comment]
3fb56add4d220f5ce3ecee56d50f433fe6e9d869
